RM = rm -f
INSTALL = install -D -m 755
# Edited for Debian GNU/Linux.
DESTDIR =
INSTALL_DIR = $(DESTDIR)/usr/man/man1
INSTALL_NAME = id3ren.1.gz

all:

debug:

install:
	${INSTALL} ${INSTALL_NAME} ${INSTALL_DIR}/${INSTALL_NAME}

clean:

