CFLAGS = -O2 -s -Wall
CC = gcc
RM = rm -f
INSTALL_DIR = ..
INSTALL_NAME = id3ren.exe
SOURCES = id3ren.c id3tag.c file.c misc.c

all:
	${CC} ${CFLAGS} -o ${INSTALL_NAME} ${SOURCES}

install: all
	copy /y ${INSTALL_NAME} ${INSTALL_DIR}\${INSTALL_NAME}

clean:
	${RM} ${INSTALL_NAME} *.o *.bak core

